# Generated by Django 3.1.3 on 2020-12-01 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='タイトル')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='価格')),
            ],
            options={
                'verbose_name': '本',
                'verbose_name_plural': '本',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('01', '決済中'), ('02', '決済OK'), ('03', '決済NG'), ('09', '決済エラー')], max_length=2, verbose_name='ステータス')),
                ('total_amount', models.PositiveIntegerField(verbose_name='金額合計')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='注文日時')),
                ('ordered_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='注文者')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='BookStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='在庫数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.book', verbose_name='本')),
            ],
            options={
                'verbose_name': '在庫',
                'verbose_name_plural': '在庫',
                'db_table': 'stock',
            },
        ),
    ]
