# Generated by Django 3.1.3 on 2020-12-01 05:12

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstock',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number', verbose_name='バージョン'),
        ),
    ]
